version: "3.6"

services:
  # NGINX
  nginx:
    image: nginx:1.19.2
    container_name: load-balancer
    depends_on:
      - chat-node
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public/certs:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443

  # Backend Node
  chat-node:
    # container_name: chat-node
    build: ./
    command: npm run dev
    working_dir: /user/src/chat-node
    environment:
      MYSQL_URI: mysql://root:secret@mysql/chat
    links:
      - mysql
    # ports:
    #   - "3000:3000"
    volumes:
      - ./:/user/src/chat-node

  # Database
  mysql:
    # container_name: mysql
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: chat
      MYSQL_HOST: mysql
    # ports:
    #   - "3306:3306"
